# Generated by Django 4.2 on 2023-04-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('bio', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('paginas', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('resumo', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='livraria.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='livraria.categoria')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='livraria.editora')),
            ],
        ),
    ]
